forge "https://forgeapi.puppetlabs.com"

mod 'gozer/nubis-nubis_prometheus',
    :git => 'https://github.com/gozer/nubis-puppet-prometheus.git',
    :ref => '12dbbe74da97c4b14b140ef0417aca327659c43f'

mod 'gozer/nubis-nubis_alertmanager',
    :git => 'https://github.com/gozer/nubis-puppet-alertmanager.git'

mod 'gozer/nubis-nubis_traefik',
    :git => 'https://github.com/gozer/nubis-puppet-traefik.git',
    :ref => '9f0c9b59424c04e446b1e3b7cb0b0ffe5799eb70'

mod 'gozer/nubis-nubis_grafana',
    :git => 'https://github.com/gozer/nubis-puppet-grafana.git',
    :ref => '36cbb5a0b4b69cdb67b552b19293df351aec8abe'

mod 'bfraser/grafana',
    :git => 'https://github.com/bfraser/puppet-grafana.git',
    :ref => '6d426d5ccc52ff23dbbcfc45290dafd224b5d2bc'
