forge "https://forgeapi.puppetlabs.com"

mod 'gozer/nubis-nubis_prometheus',
    :git => 'https://github.com/gozer/nubis-puppet-prometheus.git',
    :ref => '77f5462b2e3778295197a968e3b0d2e43ba89e96'

mod 'gozer/nubis-nubis_alertmanager',
    :git => 'https://github.com/gozer/nubis-puppet-alertmanager.git'

mod 'gozer/nubis-nubis_traefik',
    :git => 'https://github.com/gozer/nubis-puppet-traefik.git',
    :ref => '589235055e89d8b01f1f8d4d8f1949d0bb21c03f'

mod 'gozer/nubis-nubis_grafana',
    :git => 'https://github.com/gozer/nubis-puppet-grafana.git',
    :ref => '36cbb5a0b4b69cdb67b552b19293df351aec8abe'

mod 'bfraser/grafana',
    :git => 'https://github.com/bfraser/puppet-grafana.git',
    :ref => '6d426d5ccc52ff23dbbcfc45290dafd224b5d2bc'
