#!/bin/bash

OS_RELEASE=$(lsb_release -s -r)

/usr/bin/crudini --set /etc/grafana/grafana.ini server root_url /admin/executive-dashboard-$(nubis-metadata NUBIS_ENVIRONMENT)

if [ "${OS_RELEASE}" == "14.04" ]; then
    /etc/init.d/grafana-server restart
elif [ "${OS_RELEASE}" == "16.04" ]; then
    systemctl restart grafana-server.service
else
    echo "ERROR: ${OS_RELEASE} is not supported"
    exit 1
fi
