#!/bin/bash

OS_RELEASE=$(lsb_release -s -r)

eval "$(nubis-metadata)"

# replace %%ENVIRONMENT%% with actual environment
if [ "${NUBIS_ENVIRONMENT}" != "" ]; then
    find /etc/grafana -type f -name '*.json' -print0 | xargs -0 --verbose sed -i -e "s/%%ENVIRONMENT%%/$NUBIS_ENVIRONMENT/g"
fi

if [ "${OS_RELEASE}" == "14.04" ]; then
    /etc/init.d/grafana-server restart
elif [ "${OS_RELEASE}" == "16.04" ]; then
    systemctl restart grafana-server.service
else
    echo "ERROR: ${OS_RELEASE} is not supported"
    exit 1
fi
